my_list=[1,2,3,4]
print(my_list)
my_list.append(99)
my_list.insert(1,89)
print(my_list)
print(len(my_list))
my_list.pop()
print(my_list)
my_list.pop(0)
print(my_list)
l=[2,3,4,5,-90,24,10,26]
new_list=my_list+l
print(new_list)
l=my_list.copy()
l.sort()
print(*l)
cnt=l.count(2)
print(cnt)
